name: 🚀 Deploy project in GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  gh-pages-deploy:
    name: 🧩 Deploying code to gh-pages branch
    runs-on: ubuntu-latest
    steps:
      - name: 🔀 Checkout code from repository
        uses: actions/checkout@v4
      - name: 🛠 Setup Node version
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: 📦 Install dependencies
        run: npm install
      - name: 🙍‍♂️ Setup git user
        run: |
          git config user.name "Max Base (Seyyed Ali Mohammadiyeh)"
          git config user.email "maxbasecode@gmail.com"
      - name: 🏗 Deploy project
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
